steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - read_json_from_gcs
  - --region=europe-west1
  - --source=./mi_app
  - --trigger-bucket=gs://mi-bucket-proyecto
  - --allow-unauthenticated
  - --runtime=python39